MyBlogPro/App/views.py
import random

from flask import Blueprint, render_template, request, session, redirect, url_for, g
from App.models import *

blue = Blueprint('user', __name__)


# 首页
@blue.route('/')
def index():
    sorts=Sort.query.filter(Sort.num>0)
    article = Article.query.limit(6)
    page=(Article.query.count())//6+2
    data={
        'sorts':sorts,
        'article':article,
        'page':page
    }
    return render_template('home/index.html',data=data)

@blue.route('/page/<int:num>/')
def page(num):
    num=num
    sorts=Sort.query.filter(Sort.num>0)
    article = Article.query.offset((num-1)*6).limit(6)
    page=(Article.query.count())//6+2
    print(page)
    data={
        'sorts':sorts,
        'article':article,
        'page':page
    }
    return render_template('home/index.html',data=data)



@blue.route('/myindex/<string:name>/')
def myindex(name):
    data = Sort.query.filter_by(name=name).first()
    sorts =Sort.query.all()
    page=Sort.query.filter_by(name=name).first().num//6+2
    mydata = {
        'data':data,
        "sorts":sorts,
        'page':page,
    }
    return render_template('home/index.html',data=mydata)
@blue.route('/about/')
def about():
    res=request.url_root
    return render_template('home/about.html',res=res)
@blue.route('/gbook/')
def gbook():
    return render_template('home/gbook.html')
@blue.route('/info/')
def info():
    return render_template('home/info.html')

@blue.route('/infopic/')
def infopic():
    return render_template('home/infopic.html')

@blue.route('/list/')
def list():
    return render_template('home/list.html')

@blue.route('/share/')
def share():
    return render_template('home/share.html')
#后台



@blue.route('/addflink/')
def add_flink():
    return render_template('admin/add-flink.html')


@blue.route('/addnotice/')
def add_notice():
    return render_template('admin/add-notice.html')


@blue.route('/article/')
def article():
    data={
    'name':session.get('name'),
    "articles":Article.query.all()
    }
    return render_template('admin/article.html',data=data)


@blue.route('/category/')
def category():
    s =Sort.query.all()
    name = session.get('name')
    data={
        's':s,
        "name":name
    }
    return render_template('admin/category.html',data=data)
@blue.route('/comment/')
def commet():
    return render_template('admin/comment.html')
@blue.route('/flink/')
def flink():
    return render_template('admin/flink.html')
@blue.route('/index/')
def adminindex():
    if session.get("name"):
        return render_template('admin/index.html',name=session.get("name"))
    else:
        return redirect(url_for('user.login'))

@blue.route('/login/',methods=["GET","POST"])
def login():
    if request.method =="POST":
        name = request.form.get('username')
        pwd = request.form.get('userpwd')
        user=User.query.all()
        for x in user:
            if x.name !=name or x.password != pwd:
                continue
            else:
                session['name'] = name
                break
        else:
            return "账户或者密码错误"
        return redirect(url_for('user.adminindex'))
    return render_template('admin/login.html')
@blue.route('/logout/')
def logout():
    session.clear()
    return redirect(url_for('user.adminindex'))
@blue.route('/loginlog/')
def loginlog():
    return render_template('admin/loginlog.html')
@blue.route('/manageuser/')
def manage_user():
    return render_template('admin/manage-user.html')
@blue.route('/notice/')
def notice():
    return render_template('admin/notice.html')
@blue.route('/readset/')
def readset():
    return render_template('admin/readset.html')
@blue.route('/setting/')
def setting():
    return render_template('admin/setting.html')
@blue.route('/updatearticle/',methods=["GET","POST"])
def update_article():
    if request.method == "POST":
        title = request.form.get('title')
        content = request.form.get('content')
        id = request.form.get('category')
        myarticle = Article.query.filter_by(id=id).first()
        myarticle.name = title
        myarticle.content = content
        try:
            db.session.add(myarticle)
            db.session.commit()
        except:
            db.session.roolback()
            db.session.flush()
        return redirect(url_for('user.article'))
    return render_template('admin/update-article.html')

@blue.route('/aarticle/<string:article>/')
def aarticle(article):
    data = Article.query.filter_by(name=article).first()
    data={
        'data':data,
        'sort':Sort.query.all()
    }
    return render_template('admin/update-article.html',data=data)


@blue.route("/movearticle/<int:id>/")
def movearticle(id):
    mya = Article.query.filter_by(id=id).first()
    s=Sort.query.filter_by(id=mya.my_sort).first()
    c=s.num
    s.num=c-1
    if s.num ==0:
        db.session.delete(s)
    else:
        db.session.add(s)
    try:
        db.session.delete(mya)
        db.session.commit()
    except:
        db.session.roolback()
        db.session.flush()
    return redirect(url_for('user.article'))
@blue.route('/mycatedate/<int:id>/')
def mycatedate(id):
    data = Sort.query.filter_by(id=id).first()
    return render_template('admin/update-category.html',data=data)
@blue.route("/movecategory/<int:id>/")
def movecategory(id):
    mysort=Sort.query.filter_by(id=id).first()
    db.session.delete(mysort)
    try:
        db.session.commit()
    except:
        db.session.rollback()
        db.session.flush()
    return redirect(url_for('user.category'))


@blue.route('/updatecategory/',methods=["GET",'POST'])
def update_category():
    if request.method == "POST":
        myname =request.form.get("name")
        myothername=request.form.get('alias')
        myid = request.form.get('fid')
        id=int(myid)
        mysort=Sort.query.filter_by(id=id).first()
        mysort.name=myname
        mysort.othername=myothername
        try:
            db.session.commit()
        except:
            db.session.rollback()
            db.session.flush()
        return redirect(url_for('user.category'))
    return render_template('admin/update-category.html')
@blue.route('/updateflink/')
def update_flink():
    return render_template('admin/update-flink.html')
@blue.route('/addarticle/',methods=['GET','POST'])
def add_article():
    if request.method == "POST":
        title = request.form.get('title')
        content = request.form.get('content')
        tags = request.form.get('tags')
        cate = request.form.get('category')
        a = Article()
        a.name = title
        a.content = content
        a.pic=random.randint(1,12)
        if tags:
            s = Sort()
            s.name = tags
            s.num = Sort.query.filter_by(name=tags).count()+1

            try:
                db.session.add(s)
                db.session.commit()
            except:
                db.session.rollback()
                db.session.flush()
            a.my_sort = Sort.query.filter_by(name=tags).first().id
            try:
                db.session.add(a)
                db.session.commit()

            except:
                db.session.rollback()
                db.session.flush()
            return redirect(url_for('user.article'))
        else:
            a.my_sort = cate
            so = Sort.query.filter_by(id=cate).first()
            c=so.num
            so.num=c+1
            try:
                db.session.add(a)
                db.session.commit()
                try:
                    db.session.add(so)
                    db.session.commit()
                except:
                    db.session.rollback()
                    db.session.flush()
            except:
                db.session.rollback()
                db.session.flush()
            return redirect(url_for('user.article'))
    name=session.get('name')
    sorts = Sort.query.all()
    data={
        'name':name,
        'sorts':sorts
    }
    return render_template('admin/add-article.html',data=data)
@blue.route('/addcategory/',methods=['GET','POST'])
def add_category():
    if request.method == "POST":
        name = request.form.get('name')
        othername= request.form.get('alias')
        s=Sort()
        m = Sort.query.all()
        for x in m:
            if x.name == name and x.othername == othername:
                res=x.num+1
                c=Sort.query.filter_by(name=name).first()
                c.num=res
                try:
                    db.session.add(c)
                    db.session.commit()
                except:
                    db.session.roolback()
                    db.session.flush()
                break
            elif (x.name != name and x.othername == othername) or (x.name == name and x.othername != othername):
                break
            else:
                pass
        else:
            s.name = name
            s.othername=othername
            s.num=0
            try:
                db.session.add(s)
                db.session.commit()
            except:
                db.session.roolback()
                db.session.flush()
        return redirect(url_for('user.category'))
    return render_template('admin/add-category.html')
#
#
#
#
@blue.route('/register/',methods=['GET','POST'])
def register():
    if request.method == "POST":
        pwd = request.form.get('userpwd')
        checkpwd = request.form.get('checkuserpwd')
        username = request.form.get('username')
        user=User.query.all()
        for x in user:
            if username == x.name:
                return render_template('admin/register.html',data='用户名已存在')
                break

MyBlogPro/App/templates/home/index.html
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>首页_杨青个人博客 - 一个站在web前端设计之路的女技术员个人博客网站</title>
<meta name="keywords" content="个人博客,杨青个人博客,个人博客模板,杨青" />
<meta name="description" content="杨青个人博客，是一个站在web前端设计之路的女程序员个人网站，提供个人博客模板免费资源下载的个人原创网站。" />
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{{url_for('static',filename='home/css/base.css')}}" rel="stylesheet">
<link href="{{url_for('static',filename='home/css/index.css')}}" rel="stylesheet">
<link href="{{url_for('static',filename='home/css/m.css')}}" rel="stylesheet">
<script src="{{url_for('static',filename='home/js/jquery.min.js')}}" type="text/javascript"></script>
<script type="text/javascript" src="{{url_for('static',filename='home/js/comm.js')}}"></script>
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header class="header-navigation" id="header">
  <nav><div class="logo"><a href="/">杨青个人博客</a></div>
    <h2 id="mnavh"><span class="navicon"></span></h2>
    <ul id="starlist">
      <li><a href="{{ url_for('user.index') }}">网站首页</a></li>
      <li><a href="{{ url_for('user.infopic') }}">我的相册</a></li>
      <li><a href="{{ url_for('user.list') }}">我的日记</a></li>
      <li><a href="{{ url_for('user.about') }}">关于我</a></li>
      <li><a href="{{ url_for('user.gbook') }}">留言</a></li>
      <li><a href="{{ url_for('user.info') }}">内容页</a></li>
      <li><a href="{{ url_for('user.share') }}">分享</a></li>
        <li><a href="{{ url_for('user.adminindex') }}">后台系统</a></li>
    </ul>
</nav>
</header>
<article>
  <aside class="l_box">
      <div class="about_me">
        <h2>关于我</h2>
        <ul>
          <i><img src="{{url_for('static',filename='home/images/4.jpg')}}"></i>
          <p><b>杨青</b>，一个80后草根女站长！09年入行。一直潜心研究web前端技术，一边工作一边积累经验，分享一些个人博客模板，以及SEO优化等心得。</p>
        </ul>
      </div>
      <div class="wdxc">
        <h2>我的相册</h2>
        <ul>
          <li><a href="/"><img src="{{ url_for('static',filename='home/images/7.jpg') }}"></a></li>
          <li><a href="/"><img src="{{ url_for('static',filename='home/images/8.jpg') }}"></a></li>
          <li><a href="/"><img src="{{ url_for('static',filename='home/images/9.jpg') }}"></a></li>
          <li><a href="/"><img src="{{ url_for('static',filename='home/images/10.jpg') }}"></a></li>
          <li><a href="/"><img src="{{ url_for('static',filename='home/images/11.jpg') }}"></a></li>
          <li><a href="/"><img src="{{ url_for('static',filename='home/images/12.jpg') }}"></a></li>
        </ul>
      </div>
      <div class="search">
        <form action="/e/search/index.php" method="post" name="searchform" id="searchform">
          <input name="keyboard" id="keyboard" class="input_text" value="请输入关键字词" style="color: rgb(153, 153, 153);" onfocus="if(value=='请输入关键字词'){this.style.color='#000';value=''}" onblur="if(value==''){this.style.color='#999';value='请输入关键字词'}" type="text">
          <input name="show" value="title" type="hidden">
          <input name="tempid" value="1" type="hidden">
          <input name="tbname" value="news" type="hidden">
          <input name="Submit" class="input_submit" value="搜索" type="submit">
        </form>
      </div>
      <div class="fenlei">
        <h2>文章分类</h2>

          <ul>
              {% for sort in data.get('sorts') %}
                  <li><a href="{{ url_for('user.myindex',name=sort.name) }}">{{ sort.name }} ({{ sort.num }})</a></li>
              {% endfor %}

{#          <li><a href="{{ url_for('user.myindex',name='学无止境') }}">学无止境（33）</a></li>#}
{#          <li><a href="{{ url_for('user.myindex',name='日记') }}">日记（19）</a></li>#}
{#          <li><a href="{{ url_for('user.myindex',name='慢生活') }}">慢生活（520）</a></li>#}
{#          <li><a href="{{ url_for('user.myindex',name='美文欣赏') }}">美文欣赏（40）</a></li>#}
        </ul>

      </div>
      <div class="tuijian">
        <h2>站长推荐</h2>
        <ul>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
          <li><a href="/">你是什么人便会遇上什么人</a></li>
          <li><a href="/">帝国cms 列表页调用子栏目，没有则不显示栏目名称</a></li>
          <li><a href="/">第二届 优秀个人博客模板比赛参选活动</a></li>
          <li><a href="/">个人博客模板《绅士》后台管理</a></li>
        </ul>
      </div>
      <div class="links">
        <h2>友情链接</h2>
        <ul>
          <a href="http://www.yangqq.com">杨青个人博客</a> <a href="http://www.yangqq.com">杨青博客</a>
        </ul>
      </div>
      <div class="guanzhu">
        <h2>关注我 么么哒</h2>
        <ul>
          <img src="{{ url_for('static',filename='home/images/wx.jpg') }}">
        </ul>
      </div>
  </aside>
  <main class="r_box">
      {% if data.get('data')  %}
          {% for article in data.get('data').ars %}
                  <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/%d.jpg'%(article.pic)) }}"></a></i>
                    <h3><a href="/">{{ article.name }}</a></h3>
                    <p>{{ article.content | striptags }}</p>
                  </li>
          {% endfor %}

      {% else %}
          {% for a in data.get('article') %}
          <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/%d.jpg'%(a.pic)) }}"></a></i>
            <h3><a href="/">{{ a.name | striptags}}</a></h3>
            <p>{{ a.content | striptags}}</p>
            </li>
          {% endfor %}

{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/1.jpg') }}"></a></i>#}
{#      <h3><a href="/">你是什么人便会遇上什么人</a></h3>#}
{#      <p>有时就为了一句狠话，像心头一口毒钉，永远麻痺着亲密感情交流。恶言，真要慎出，平日多誠心爱语，乃最简易之佈施。</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/2.jpg') }}"></a></i>#}
{#      <h3><a href="/">爱情没有永远，地老天荒也走不完</a></h3>#}
{#      <p>也许，爱情没有永远，地老天荒也走不完，生命终结的末端，苦短情长。站在岁月的边端，那些美丽的定格，心伤的绝恋，都被四季的掩埋，一去不返。徒剩下这荒芜的花好月圆，一路相随，流离天涯背负了谁的思念？</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/3.jpg') }}"></a></i>#}
{#      <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>#}
{#      <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/4.jpg') }}"></a></i>#}
{#      <h3><a href="/">擦肩而过</a></h3>#}
{#      <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>#}
{#    </li>#}
{#     <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/1.jpg') }}"></a></i>#}
{#      <h3><a href="/">你是什么人便会遇上什么人</a></h3>#}
{#      <p>有时就为了一句狠话，像心头一口毒钉，永远麻痺着亲密感情交流。恶言，真要慎出，平日多誠心爱语，乃最简易之佈施。</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/2.jpg') }}"></a></i>#}
{#      <h3><a href="/">爱情没有永远，地老天荒也走不完</a></h3>#}
{#      <p>也许，爱情没有永远，地老天荒也走不完，生命终结的末端，苦短情长。站在岁月的边端，那些美丽的定格，心伤的绝恋，都被四季的掩埋，一去不返。徒剩下这荒芜的花好月圆，一路相随，流离天涯背负了谁的思念？</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/3.jpg') }}"></a></i>#}
{#      <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>#}
{#      <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/4.jpg') }}"></a></i>#}
{#      <h3><a href="/">擦肩而过</a></h3>#}
{#      <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>#}
{#    </li>#}
{#    <li>#}
{#      <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>#}
{#      <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/5.jpg') }}"></a></i>#}
{#      <h3><a href="/">擦肩而过</a></h3>#}
{#      <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/6.jpg') }}"></a></i>#}
{#      <h3><a href="/">女孩都有浪漫的小情怀——浪漫的求婚词</a></h3>#}
{#      <p>还在为浪漫的求婚词而烦恼不知道该怎么说吗？女孩子都有着浪漫的小情怀，对于求婚更是抱着满满的浪漫期待，也希望在求婚那一天对方可以给自己一个最浪漫的求婚词。</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/7.jpg') }}"></a></i>#}
{#      <h3><a href="/">你是什么人便会遇上什么人</a></h3>#}
{#      <p>有时就为了一句狠话，像心头一口毒钉，永远麻痺着亲密感情交流。恶言，真要慎出，平日多誠心爱语，乃最简易之佈施。</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/8.jpg') }}"></a></i>#}
{#      <h3><a href="/">爱情没有永远，地老天荒也走不完</a></h3>#}
{#      <p>也许，爱情没有永远，地老天荒也走不完，生命终结的末端，苦短情长。站在岁月的边端，那些美丽的定格，心伤的绝恋，都被四季的掩埋，一去不返。徒剩下这荒芜的花好月圆，一路相随，流离天涯背负了谁的思念？</p>#}
{#    </li>#}
{#    <li><i><a href="/"><img src="{{ url_for('static',filename='home/images/9.jpg') }}"></a></i>#}
{#      <h3><a href="/">擦肩而过</a></h3>#}
{#      <p>《擦肩而过》文/清河鱼 编绘/天朝羽打开一扇窗，我不曾把你想得平常。看季节一一过往。你停留的那个地方，是否依然花儿开放？在夜里守靠着梦中的，想那仿佛前世铭刻进心肠的</p>#}
{#    </li>#}

    {% endif %}
<div class="pagelist">
    {% for x in range(1,data.get('page')) %}
        <a href="{{ url_for('user.page',num=x) }}" class="curPage">{{ x }}</a>&nbsp;&nbsp;
    {% endfor %}
</div>
  </main>
</article>
<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">杨青个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
<a href="#" class="cd-top">Top</a>
</body>
</html>